import { themeToCss } from './cssVars';
import { presets } from './presets';

/**
 * The stylesheet behind `src/styles/tokens.css`: `:root` gets the light theme, and each preset is
 * selectable with `data-mt-theme="<name>"`. Written to disk by `scripts/build-tokens.ts`.
 */
export function generateTokensCss(): string {
  const header =
    '/* Generated by scripts/build-tokens.ts from src/theme/presets. Do not edit by hand. */\n';
  const rules = Object.values(presets).map((theme) =>
    themeToCss(
      theme,
      theme.name === 'light'
        ? `:root,\n[data-mt-theme='light']`
        : `[data-mt-theme='${theme.name}']`,
    ),
  );
  return [header, ...rules].join('\n');
}
